#!/usr/bin/env node
// Exports the Letterlock ABI from the Foundry artifact to
//   contracts/abi/Letterlock.json          (plain JSON, for any language)
//   packages/letterlock/src/abi.ts         (viem-style `as const`, for the SDK)
//
//   (cd contracts && forge build) && node contracts/script/export-abi.mjs           # write
//   (cd contracts && forge build) && node contracts/script/export-abi.mjs --check   # exit 1 if stale
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const contracts = join(dirname(fileURLToPath(import.meta.url)), "..");
const repo = join(contracts, "..");
const artifact = join(contracts, "out", "Letterlock.sol", "Letterlock.json");
const jsonOut = join(contracts, "abi", "Letterlock.json");
const tsOut = join(repo, "packages", "letterlock", "src", "abi.ts");

if (!existsSync(artifact)) {
  console.error(`missing ${relative(repo, artifact)}: run \`forge build\` in contracts/ first`);
  process.exit(1);
}
const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
if (!Array.isArray(abi) || abi.length === 0) throw new Error("artifact has no ABI");

const json = `${JSON.stringify(abi, null, 2)}\n`;
const ts = `// Generated by contracts/script/export-abi.mjs from contracts/src/Letterlock.sol. Do not edit by hand.
// Deployments (address, chain, txs): deployments/<chainId>.json.
export const letterlockAbi = ${JSON.stringify(abi, null, 2)} as const;
`;

const outputs = [
  [jsonOut, json],
  [tsOut, ts],
];
if (process.argv.includes("--check")) {
  const stale = outputs.filter(([path, body]) => !existsSync(path) || readFileSync(path, "utf8") !== body);
  for (const [path] of stale) console.error(`stale: ${relative(repo, path)}`);
  if (stale.length) process.exit(1);
  console.log(`ABI up to date (${abi.length} entries)`);
} else {
  for (const [path, body] of outputs) {
    writeFileSync(path, body);
    console.log(`wrote ${relative(repo, path)}`);
  }
  console.log(`${abi.length} ABI entries`);
}
